### 

@host = http://localhost:8080


### 

# @name register

POST {{host}}/api/auth/register HTTP/1.1

{
  "confirmPassword": "kratosgado",
  "email": "katosgado@gmail.com",
  "name": "Kratosgado",
  "password": "kratosgado"
}


### 

POST {{host}}/api/auth/login HTTP/1.1

{
  "password": "",
  "username": ""
}


### 

GET {{host}}/ HTTP/1.1
