logging:
  level:
    com.kratosgado.chatapp: DEBUG
    org.springframework.web: INFO
server:
  port: 8080

spring:
  application:
    name: chatapp

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:chatapp}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:940ff3dce8ce688ebb9cd5c866cedd3b3d423d5ca31342d06402569949991832}
    expiration-time: ${JWT_EXPIRATION_TIME:36000000}
