logging:
  level:
    com.kratosgado.chatapp: INFO
    org.springframework.web: WARN
server:
  port: 8080

spring:
  application:
    name: chatapp

  datasource:
    url: ${DB_URL}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: ${JWT_EXPIRATION_TIME:36000000}
